Add event date and location
COSCUP/coscup.org pull request #19
Opened 2024-09-04 09:46 UTC by rileychh

(Depends on #13, will edit later)

Contributes to #7.

2024-09-05 11:25 UTC, rileychh commented on components/LeafletMap.vue
> +])
問一下，這段向 Overpass API 查詢建築物外框的程式碼，是不是可以寫成 Data loader 或是寫死查詢結果？它不受外部影響，每次的結果都一樣。

2024-09-06 10:11 UTC, mirumodapon commented on components/LeafletMap.vue
> +])
看起來這個值不太會改變，感覺用loader 比較理想

2024-09-06 17:52 UTC, rileychh commented on components/LeafletMap.vue
> +])
0c2dc21

2024-09-07 03:23 UTC, mirumodapon requested changes

2024-09-07 03:23 UTC, mirumodapon commented on components/VPButton.vue
> +  return props.tag || props.href ? 'a' : 'button'
我在想這裡應該是想要用各種不一樣的 tag 嗎？那後面可能要括號，不然邏輯不一樣。

Currently ```(props.tag || props.href) ? 'a' : 'button'```
Must be ```props.tag || ( props.href ? 'a' : 'button')```

2024-09-07 03:23 UTC, mirumodapon commented on components/VPButton.vue
> +  white-space: nowrap;
因為上面提供了不同 tag 的參數，許願加上 ```cursor: pointer```

2024-09-07 03:23 UTC, mirumodapon commented on components/VPButton.vue
> +.VPButton.big {
好像中大兩個排在一起看起來長寬比不一樣，是故意的嗎（？
（美感不佳的我提出的麻瓜疑問 ＱＱ

2024-09-07 03:23 UTC, mirumodapon commented on eslint.config.js
> +      'style/no-multi-spaces': ['error', { ignoreEOLComments: true }],
怎麼偷偷加 eslint rule 🤣

2024-09-07 03:45 UTC, rileychh commented on components/VPButton.vue
> +  return props.tag || props.href ? 'a' : 'button'
他的意思是：
1. 如果有設 `tag`，標籤就是 `tag` 的值
2. 如果有設 `href`，標籤就是 `a`，不然就是 `button`

2024-09-07 03:47 UTC, rileychh commented on components/VPButton.vue
> +  white-space: nowrap;
從最終的結果來看，不管標籤是 `a` 還是 `button`，都有 `hover: { cursor: pointer }` 的效果了。還有哪些情況是沒有改變游標樣式的嗎？

2024-09-07 03:47 UTC, mirumodapon commented on components/VPButton.vue
> +  return props.tag || props.href ? 'a' : 'button'
所以是只接受 ‘a' or 'button' 嗎？

2024-09-07 03:48 UTC, rileychh commented on components/VPButton.vue
> +.VPButton.big {
不會有中、大按鈕排在一起的用法，所以應該沒有什麼好擔心的。

2024-09-07 03:50 UTC, rileychh commented on eslint.config.js
> +      'style/no-multi-spaces': ['error', { ignoreEOLComments: true }],
我認為對齊行尾註解對於解釋程式碼很有幫助，所以我就加上去了。
見[此處](https://github.com/COSCUP/coscup.org/pull/19/files#diff-eae3c8286fa46306621ffd58cf92d295b076a5339550ec63e5159104456a735eR11-R21)

2024-09-07 03:53 UTC, rileychh commented on components/VPButton.vue
> +  return props.tag || props.href ? 'a' : 'button'
`tag` 中應該是任何標籤名稱都可以，這邊是在透過 `href` 決定 fallback 的值。

2024-09-07 05:20 UTC, rileychh commented on components/VPButton.vue
> +  return props.tag || props.href ? 'a' : 'button'
結果 @mirumodapon 是對的 :sweat_smile: 

這看起來的確和預期的行為不相符，所以我去上游[開了 PR](https://redirect.github.com/vuejs/vitepress/pull/4185) 了。看看那邊的結果如何吧！

2024-09-07 05:34 UTC, rileychh commented on components/VPButton.vue
> +  return props.tag || props.href ? 'a' : 'button'
果然是被 merge 了。我在 9930628 做了相同的修改~

2024-09-07 10:21 UTC, mirumodapon commented on components/LeafletMap.vue
> +])
我覺得可以不用耶，畢竟也都留相關連結了

2024-09-07 10:27 UTC, mirumodapon commented on components/VPButton.vue
> +  return props.tag || props.href ? 'a' : 'button'
👍

2024-09-07 10:29 UTC, mirumodapon approved these changes
LGTM (交通資訊待捕)

2024-09-07 13:53 UTC, merged