feat: resize images & fix Carousel (拆掉 commit 再重新 push)
COSCUP/coscup.org pull request #25
Opened 2024-10-01 16:29 UTC by bessyhuang

2024-10-03 06:22 UTC, rileychh requested changes
看起來很棒，只有一些小問題。能讓滑鼠在 `Swiper` 上有「左、右」箭頭能點擊嗎？這樣會比較容易瀏覽相片。

另外，在手機上相片好像太小張了！試試看能不能讓元件的大小根據視窗的寬度縮放（或者在寬度不足時減少一次瀏覽的張數）。

<img src="https://github.com/user-attachments/assets/bc0c8270-4f45-4b24-9f55-25b48b340c98" align="center" width="300px" />

2024-10-03 06:22 UTC, rileychh commented on components/FlickrCarousel.vue
> +  </swiper-container>
```diff
diff --git a/components/FlickrCarousel.vue b/components/FlickrCarousel.vue
index 147cb53..7db7932 100644
--- a/components/FlickrCarousel.vue
+++ b/components/FlickrCarousel.vue
@@ -1,5 +1,5 @@
 <script setup>
-import { SwiperSlide } from 'swiper/vue'
+import { Swiper, SwiperSlide } from 'swiper/vue'
 import 'swiper/css'
 import 'swiper/swiper-bundle.css'
 import { register } from 'swiper/element/bundle'
@@ -24,7 +24,7 @@ const images = [image1, image2, image3, image4, image5, image6, image7, image8,
 </script>
 
 <template>
-  <swiper-container
+  <Swiper
     :autoplay="{ delay: 2500, disableOnInteraction: false }"
     :loop="true"
     :pagination="{ clickable: true }"
@@ -38,7 +38,7 @@ const images = [image1, image2, image3, image4, image5, image6, image7, image8,
     >
       <img :src="src">
     </SwiperSlide>
-  </swiper-container>
+  </Swiper>
 </template>
 
 <style>
```

看起來 `swiper-container` 不是一個元件，所以我猜你指的是 `Swiper`。這樣改後就沒有錯誤了~

2024-10-06 14:12 UTC, mirumodapon commented on components/FlickrCarousel.vue
> +  </swiper-container>
`swiper-container` 其實是這個套件定義的 web component，所以在 register 過後，瀏覽器應該是認識這個 tag 的

https://github.com/nolimits4web/swiper/blob/40a705e5bcadf2ee2ee90591ff9ed95c1aaf9026/src/swiper-element.mjs#L309

2024-10-06 14:31 UTC, mirumodapon commented on components/FlickrCarousel.vue
> +  </swiper-container>
補充一下，這邊的 `swiper-container` 是套件提供的 web component，在 register 之後， 瀏覽器應該就會認識這個 tag 了，不過這個註冊是直接註冊到 web component，所以對 vue 來說是未知的，所以才會有 vue 的警告。

https://github.com/nolimits4web/swiper/blob/40a705e5bcadf2ee2ee90591ff9ed95c1aaf9026/src/swiper-element.mjs#L309

2024-10-06 14:33 UTC, mirumodapon approved these changes
LGTM, it is better if there is dynamic import at swiper image.

2024-10-06 16:30 UTC, bessyhuang commented
![image](https://github.com/user-attachments/assets/c127f6c2-f314-487e-9ae3-245461a7cd7f)
圖片顯示 待修

2024-10-07 03:18 UTC, rileychh commented on components/FlickrCarousel.vue
> +  </swiper-container>
謝謝你的指正！剛剛讀了一下 Swiper 的文件，好像 Swiper Vue 元件在未來會被棄用，並建議改用 web component。如果是這樣的話，是不是裡面的 Swiper 也要改用 web component，以求一致性呢？

2024-10-07 03:20 UTC, rileychh commented
> LGTM, it is better if there is dynamic import at swiper image.

為什麼動態引入會比較好呢？用靜態引入可以減少需要的 JavaScript 程式量。

2024-10-22 05:37 UTC, rileychh commented on components/FlickrCarousel.vue
> +register()
沒有要用 `swiper/element` (web components) 的話就不需要 import 和 register 了喔

2024-10-22 05:37 UTC, rileychh commented on components/FlickrCarousel.vue
> +      <img :src="src">
考慮為圖片加上 `alt` 屬性

2024-12-01 14:30 UTC, bessyhuang commented on components/FlickrCarousel.vue
> +register()
`import { register } from 'swiper/element/bundle'` 會用到喔！
因為如果移除的話，slides 會動不了

2024-12-01 14:30 UTC, bessyhuang commented on components/FlickrCarousel.vue
> +      <img :src="src">
好，沒問題！

2024-12-08 09:06 UTC, rileychh commented on components/FlickrCarousel.vue
> +  </swiper-container>
在 819b77425ab18a2128448d3bc136c50f08ece01a 改用 Swiper Element 了。

2024-12-08 09:33 UTC, rileychh approved these changes

2024-12-08 09:34 UTC, merged